services:
  basket-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true
    name: ecommerce-network
