services:

  identity-service:
    build:
      context: .
      dockerfile: src/IdentityService/IdentityService.API/Dockerfile
    ports:
      - "5000:80"
    networks:
      - ecommerce

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    ports:
      - "5001:80"
    networks:
      - ecommerce

  catalog-service:
    build:
      context: .
      dockerfile: src/CatalogService/CatalogService.API/Dockerfile
    ports:
      - "5002:80"
    networks:
      - ecommerce

  basket-service:
    build:
      context: .
      dockerfile: src/BasketService/BasketService.API/Dockerfile
    ports:
      - "5003:80"
    networks:
      - ecommerce

  payment-service:
    build:
      context: .
      dockerfile: src/PaymentService/PaymentService.API/Dockerfile
    ports:
      - "5004:80"
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
